name: Build & Publish Release APK

on:
  push:
    tags:
      - 'v*'
    branches: ["master"]

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build, test, and lint
        run: ./gradlew clean assembleRelease
      - name: List
        run: ls -alR ./app/build/outputs/apk/
#      - uses: dev-drprasad/delete-tag-and-release@v1.1
#        name: Delete latest alpha tag and release
#        with:
#          tag_name: latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.APK_BUILD_ACTION }}
#      - name: Sleep for 30 seconds, to allow the tag to be deleted
#        run: sleep 30s
#        shell: bash
      - uses: ncipollo/release-action@v1.14.0
        name: Create new tag and release and upload artifacts
        with:
          name: latest
          commit: master
          tag: latest
          artifacts: "app/build/outputs/apk/alpha/release/app-release-unsigned.apk"
          body: This is the latest Alpha version of the app (autogenerated).
          token: ${{ secrets.APK_BUILD_ACTION }}
          generateReleaseNotes: true